"""doctor model add new fields

Revision ID: e41989e9ee62
Revises: 8c3dd8e28cc6
Create Date: 2025-12-05 18:45:41.619718

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e41989e9ee62'
down_revision: Union[str, Sequence[str], None] = '8c3dd8e28cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
doctorstatus = postgresql.ENUM(
    "PENDING", "APPROVED", "REJECTED", "SUSPENDED",
    name="doctorstatus"
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    doctorstatus.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('license_number', sa.String(length=100), nullable=False))
    op.add_column('doctors', sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED',
                                                                 name='doctorstatus', create_type=False),
                                       nullable=False))
    op.add_column('doctors', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('doctors', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('doctors', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_unique_constraint(None, 'doctors', ['license_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctors', type_='unique')
    op.drop_column('doctors', 'updated_at')
    op.drop_column('doctors', 'created_at')
    op.drop_column('doctors', 'rejection_reason')
    op.drop_column('doctors', 'status')
    op.drop_column('doctors', 'license_number')
    # ### end Alembic commands ###
